In [2]:
print('hi')

hi

In [3]:

print ('HI')
import streamlit as st
import sqlite3
conn = sqlite3.connect('Project.db')


def execute_query(conn, query):
    try:
        cursor = conn.cursor()
        cursor.execute(query)
        conn.commit()
        return cursor
    except sqlite3.Error as e:
        #st.error(f"Error executing SQL query: {e}")
        pass
    return None

# cursor = conn.cursor()
# cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
# conn.commit()
# for table in cursor:
#     print(table)

# query = "SELECT name FROM sqlite_master WHERE type='table';"
# for table in execute_query(conn, query):
#     print(table)
git branch -D master
git checkout main

HI

In [16]:
df = pd.read_sql_query("SELECT * from JobPost order by id desc limit 5", conn)
df

     id companyid  ... isit isposted
0  None      None  ...    1        0
1  None      None  ...    1        0
2  None      None  ...    1        0
3  None      None  ...    1        0
4  None      None  ...    1        0

[5 rows x 14 columns]